# Generated by Django 2.2.10 on 2020-09-03 00:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 0, 54, 1, 516262, tzinfo=utc)),
        ),
    ]
