# Generated by Django 3.1 on 2020-09-08 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20200904_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 8, 14, 30, 43, 506410, tzinfo=utc)),
        ),
    ]
