# Generated by Django 3.1 on 2020-09-17 13:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20200908_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 13, 18, 24, 431955, tzinfo=utc)),
        ),
    ]
