# Generated by Django 3.1 on 2020-09-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('red', 'Rosso'), ('lightgrey', 'Grigio'), ('lightblue', 'Blu'), ('green', 'Verde')], default='lightgrey', max_length=10),
        ),
    ]
