# Generated by Django 2.2.10 on 2020-08-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='area',
        ),
        migrations.AddField(
            model_name='area',
            name='garden',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Garden'),
        ),
        migrations.AddField(
            model_name='location',
            name='garden',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Garden'),
        ),
    ]
