# Generated by Django 2.2.10 on 2020-08-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200826_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='garden',
        ),
        migrations.AddField(
            model_name='garden',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Location'),
        ),
        migrations.AddField(
            model_name='garden',
            name='last_rain',
            field=models.DateTimeField(default=None, verbose_name='date of last_rain'),
        ),
        migrations.AlterField(
            model_name='area',
            name='last_irrigation',
            field=models.DateTimeField(verbose_name='date of irrigation'),
        ),
    ]
