# Generated by Django 2.2.10 on 2020-08-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200827_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='irrigation_type',
            field=models.CharField(choices=[('S', 'Manuale'), ('C', 'Calendario'), ('I', 'Intelligente')], default='M', max_length=1),
        ),
    ]
