# Generated by Django 2.2.10 on 2020-08-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_area_irrigation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='irrigation_type',
            field=models.CharField(choices=[('M', 'Manuale'), ('C', 'Calendario'), ('S', 'Intelligente')], default='M', max_length=1),
        ),
    ]
