# Generated by Django 2.2.10 on 2020-09-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_garden_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='next_rain',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
