# Generated by Django 2.2.10 on 2020-09-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_garden_next_rain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='next_rain',
            field=models.DateTimeField(default=None),
        ),
    ]
