# Generated by Django 2.2.10 on 2020-09-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_garden_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
