# Generated by Django 2.2.10 on 2020-09-17 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200917_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irrigation',
            old_name='duration',
            new_name='end',
        ),
        migrations.AddField(
            model_name='irrigation',
            name='start',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
