# Generated by Django 2.2.10 on 2020-09-18 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20200917_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='image',
            field=models.CharField(choices=[('cover/balcony.jpg', 'Pianta'), ('cover/terrace.jpg', 'Albero'), ('cover/garden.jpg', 'Prato'), ('cover/vegetable.jpg', 'Verdura'), ('cover/flower.jpg', 'Fiore')], default='cover/balcony.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='garden',
            name='next_rain',
            field=models.DateTimeField(default=datetime.date(2020, 9, 18)),
        ),
    ]
