# Generated by Django 2.2.10 on 2020-09-26 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20200918_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='next_rain',
            field=models.DateTimeField(default=datetime.date(2020, 9, 26)),
        ),
    ]
