# Generated by Django 2.2.10 on 2020-09-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20200926_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irrigation',
            old_name='irrigation',
            new_name='date',
        ),
    ]
