# Generated by Django 2.2.10 on 2020-09-29 22:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20200926_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='next_rain',
            field=models.DateTimeField(default=datetime.date(2020, 9, 30)),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='CalendarIrrigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('0', 'ogni giorno'), ('1', 'giorni alterni'), ('2', 'ogni 2 giorni'), ('3', 'ogni 3 giorni'), ('4', 'ogni 4 giorni'), ('5', 'ogni 5 giorni'), ('7', 'una volta a settimana'), ('10', 'ogni 10 giorni'), ('14', 'un volta ogni due settimane')], default='2', max_length=1)),
                ('duration', models.TimeField()),
                ('area', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Area')),
            ],
        ),
    ]
