# Generated by Django 2.2.10 on 2020-09-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20200930_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarirrigation',
            name='duration',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('40', '40'), ('30', '30'), ('45', '45'), ('50', '50'), ('55', '55'), ('60', '60')], max_length=2),
        ),
    ]
