# Generated by Django 2.2.10 on 2020-10-01 10:17

from django.db import models, migrations


def load_location_from_fixture(apps, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "location")

def delete_location(apps, schema_editor):
    location = apps.get_model("dashboard", "Location")
    location.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20200930_2338'),
    ]

    operations = [
        migrations.RunPython(load_location_from_fixture, delete_location)
    ]
