# Generated by Django 2.2.10 on 2020-10-20 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20201005_1325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalendarIrrigation',
            new_name='ScheduledIrrigation',
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Area'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data di irrigazione'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email_notification',
            field=models.BooleanField(default=True, verbose_name='Notifiche email'),
        ),
    ]
