# Generated by Django 2.2.10 on 2020-10-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20201020_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledirrigation',
            name='hour',
            field=models.TimeField(default='6:00', verbose_name='Orario'),
        ),
    ]
