# Generated by Django 2.2.10 on 2020-10-22 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_scheduledirrigation_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='position',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='position',
        ),
        migrations.AlterField(
            model_name='scheduledirrigation',
            name='hour',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Orario'),
        ),
    ]
