# Generated by Django 3.1 on 2020-10-27 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_scheduledirrigation_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledirrigation',
            name='hour',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Orario'),
        ),
    ]
