# Generated by Django 2.2.10 on 2020-11-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20201022_1513'),
        ('dashboard', '0032_auto_20201027_1146'),
    ]

    operations = [
    ]
