# Generated by Django 2.2.10 on 2020-12-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20201123_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
