# Generated by Django 2.2.10 on 2020-12-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_garden_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='relay',
            field=models.IntegerField(blank=True, null=True, verbose_name='Interruttore'),
        ),
        migrations.AddField(
            model_name='garden',
            name='ip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Indirizzo Ip Esp32'),
        ),
        migrations.AlterField(
            model_name='area',
            name='last_irrigation',
            field=models.DateTimeField(default='2012-01-01 00:01', editable=False, verbose_name='Ultima irrigazione'),
        ),
    ]
