# Generated by Django 3.1.6 on 2021-02-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_rain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledirrigation',
            name='duration',
            field=models.CharField(choices=[('1', '1 minuto'), ('2', '2 minuti '), ('3', '3 minuti '), ('4', '4 minuti '), ('5', '5 minuti '), ('6', '6 minuti '), ('7', '7 minuti '), ('8', '8 minuti '), ('9', '9 minuti '), ('10', '10 minuti'), ('11', '11 minuti '), ('12', '12 minuti '), ('13', '13 minuti '), ('14', '14 minuti '), ('15', '15 minuti '), ('20', '20 minuti '), ('25', '25 minuti '), ('30', '30 minuti '), ('40', '40 minuti '), ('45', '45 minuti '), ('50', '50 minuti '), ('55', '55 minuti '), ('60', '60 minuti ')], default='20', max_length=100, verbose_name='durata'),
        ),
        migrations.AlterField(
            model_name='scheduledirrigation',
            name='frequency',
            field=models.CharField(choices=[('1', 'ogni giorno'), ('2', 'ogni 2 giorni'), ('3', 'ogni 3 giorni'), ('4', 'ogni 4 giorni'), ('5', 'ogni 5 giorni'), ('7', 'una volta a settimana'), ('10', 'ogni 10 giorni'), ('14', 'una volta ogni due settimane')], default='2', max_length=10, verbose_name='frequenza'),
        ),
    ]
